# Generated by Django 3.2 on 2022-01-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(db_column='Symbol', max_length=10, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=40, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=40, null=True)),
                ('founded', models.IntegerField(blank=True, db_column='Founded', null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=40, null=True)),
                ('availablecash', models.IntegerField(blank=True, db_column='AvailableCash', null=True)),
            ],
            options={
                'db_table': 'Investor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('tdate', models.DateField(db_column='tDate', primary_key=True, serialize=False)),
                ('tquantity', models.IntegerField(blank=True, db_column='TQuantity', null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.OneToOneField(db_column='Symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Stocks_Apps.company')),
                ('tdate', models.DateField(db_column='tDate')),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('tdate', models.OneToOneField(db_column='tDate', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Stocks_Apps.stock')),
                ('bquantity', models.IntegerField(blank=True, db_column='BQuantity', null=True)),
            ],
            options={
                'db_table': 'Buying',
                'managed': False,
            },
        ),
    ]
